name: preview_knobs
description: Define custom panel for updating a set of properties.
version: 0.0.1-alpha
homepage: https://github.com/aloisdeniel/preview_knobs

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
