name: publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'

      # Build

      - name: 📦  Install Dependencies 
        run: flutter packages get

      - name: 🧹 Format 
        run: flutter format --set-exit-if-changed .

      - name: 📊 Analyze 
        run: flutter analyze lib

      # Build (Demo)

      - name: 📦 [Demo] Install Dependencies 
        working-directory: example
        run: flutter packages get

      - name: 📊 [Demo] Analyze 
        working-directory: example
        run: flutter analyze lib

      - name: 🔧 [Demo] Build demo tests 
        working-directory: example
        run: flutter build web --base-href /knobs/

      # Publish

      - name: 🚀 Publish package 
        run: flutter packages get
      
      - name: 🚀 [Demo] Deploy demo website 
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages 
          folder: example/build/web/